# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: downloadertask@1
  inputs:
    connectionId: 'cw09.compuware.com:47623#'
    runtimeConfig: 'TPZP'
    ispwUserId: 'ispwtpz'
    password: 'ispw09'
    windowsTopazWorkbenchCliHome: 'C:\Topaz\WorkbenchCLI'
    windowsSourceDownloadLocation: 'C:\ces_20'
    downloadSourceType: 'Repository'
    stream: 'topaz'
    application: 'hary'
    repositoryLevel: 'dev2'
    levelOption: 'SelectedLevelOnly'
    componentTypes: 'cob'