# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
 
trigger:
- master

pool:
  name: server

steps:


- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    method: 'GET'
    headers: |
      {
      "Content-Type":"application/json", 
      "PlanUrl": "$(system.CollectionUri)", 
      "ProjectId": "$(system.TeamProjectId)", 
      "HubName": "$(system.HostType)", 
      "PlanId": "mayank bro", 
      "JobId": "mayank bro", 
      "TimelineId": "mayank bro", 
      "TaskInstanceId": "$(system.TaskInstanceId)", 
      "AuthToken": "$(system.AccessToken)"
      }
    waitForCompletion: 'false'
  
