# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: azure-deveops-ispw-operation-task@1
  inputs:
    connectionId: 'cw09.compuware.com:47624#1047 - Latin 1'
    cesUrl: 'http://172.19.173.31:48226'
    cesSecretToken: '$(cesToken)'
    action: 'RegressAssignment'
    request: |
      #The following messages are commented out to show how to use the 'Request' field.
      #Click on the help button to the right of the screen for examples of how to populate this field based on 'Action' type
       #
       #For example, if you select GenerateTasksInAssignment for 'Action' field,
      # you may populate the following properties in 'Request' field.
       # The property value should be based on your own container ID and level.
       #
       assignmentId=HARY008363
       level=STG1
    skipWaitingForSetCompletion: false
    showResponseBodyInConsole: true