# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: default

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  -task: downloadertask@1
    inputs:
      connectionId: 'cw09.compuware.com:47624#'
      runtimeConfig: 'tptp'
      ispwUserId: 'ispwtpz'
      password: 'ispw09'
      windowsTopazWorkbenchCliHome: 'C:\Topaz\WorkbenchCLI'
      windowsSourceDownloadLocation: 'C:\Topaz'
      downloadSourceType: 'Container'
      containerType: 'Assignment'
      containerId: 'HARY008363'